name: Update templates

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/update_templates.yml'
      - 'scripts/**'
      - 'template.json'
  # Run every day
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  update_templates:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 
        with:
          ref: ${{ github.head_ref }}
      - uses: cachix/install-nix-action@v25
      - run: nix run
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update template lists
      
